### ISSUE TITLE
ReLU notation 4.5.4

### ISSUE THREAD

**Issue by ncherel** [tomepel/Technical_Book_DL#6]
First of all, awesome job. The book is really impressive and helpful.

One remark as I'm going through the book: 
Section 4.5.4 Leaky-ReLU function, equation 4.9 and 4.10:
"l - ReLU" really looks like "1 - ReLU" (one minus ReLU(x)) on the PDF.
It's really confusing.

**Comment by tomepel** [comment]
This was indeed a poor choice on my account. I modified both the text and the corresponding figure.

Thanks
